version: "2"
services:
  web:
    image: gitlab.nibor.me:4567/arcandiers/rust-admin:$CI_BUILD_REF_NAME
    environment:
      - VIRTUAL_HOST=${ENV_TEST_URL}
      - VIRTUAL_PORT=80
    network_mode: bridge
