version: "2"
services:
  web:
    image: gitlab.nibor.me:4567/arcandiers/rust-admin:$CI_BUILD_REF_NAME
    environment:
      - VIRTUAL_HOST=${CI_BUILD_REF_NAME}.rust-admin.nibor.me
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
      - LETSENCRYPT_HOST=develop.rust-admin.nibor.me
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    network_mode: bridge