version: "2"
services:
  web:
    image: gitlab.nibor.me:4567/arcandiers/rust-admin:latest
    environment:
      - VIRTUAL_HOST=${ENV_PROD_URL},www.${ENV_TEST_URL}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${ENV_PROD_URL},www.${ENV_TEST_URL}
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      - HTTPS_METHOD=noredirect
    network_mode: bridge
